### ISSUE TITLE
#US_11 Como usuario visitante quiero visualizar las inversiones mas populares entre los usuarios de la app para conocer hacia donde va el mercado.

### ISSUE THREAD

**Issue by Malvina989** [TomiLencina/ISPC-Proyecto-integrador-full-stack-#19]

**Comment by ElizabethChialva** [comment]
#US_72Como usuario premium quiero copiar estrategias operativas de los mejores inversores del mundo para obtener los mejores dividendos
#Us 73 Como usuario premium quiero encontrar menús en los que tenga acceso a la información que comparten otros usuarios en tiempo real y poder interactuar con ellos
