### ISSUE TITLE
#TK_12 Armar Modelado de BD (modelo relacional)

### ISSUE THREAD

**Issue by TomiLencina** [TomiLencina/ISPC-Proyecto-integrador-full-stack-#26]

**Comment by ahroncich7** [comment]
@Malvina989 fijate la hoja 3 del draw.io. Ahí arme un bosquejo del Mod relacional que sale del DER. Creo que le faltaría definir el dominio de cada atributo (varchar, int, etc)

https://app.diagrams.net/#G1priEx-4zkAwjVsZJ8QH2IeIyVe86Q_4T

**Comment by Malvina989** [comment]
Buenísimo Ale! @ahroncich7
