### ISSUE TITLE
Definir nombre para nuestro proyecto

### ISSUE THREAD

**Issue by Malvina989** [TomiLencina/ISPC-Proyecto-integrador-full-stack-#3]
En forma conjunta

**Comment by ahroncich7** [comment]
Buenas. Propongo Tidy-Fi (de Tidy Finances, "finanzas ordenadas")
Suena "techy" y creo que se puede hacer un buen logo al ser un nombre corto.

**Comment by ahroncich7** [comment]
También podemos poner un nombre ficticio a la empresa de desarrollo de software (para lo de SGC)

**Comment by Malvina989** [comment]
Hola! Está bueno Tidy Finances, pero no me convence la abreviación, como que hay que explicar de dónde viene, y si no me decías cómo sonaba no lo sacaba. Igual yo ya me encariñé con Controlling!

**Comment by Nicolaslucero01** [comment]
Buenas, como andan? A mi se me ocurrió Secure Wallet o Safe Wallet (billetera segura). Igual mucho no me convence, no se que opinan ustedes. :)

**Comment by ahroncich7** [comment]
> Buenas, como andan? A mi se me ocurrió Secure Wallet o Safe Wallet (billetera segura). Igual mucho no me convence, no se que opinan ustedes. :)

No me convence porque suena a que la app es una wallet y que permite transacciones seguras. Es decir, suena a otra cosa.

**Comment by ahroncich7** [comment]
Tiro tormenta (descarte varias que ya existian como "Money Keeper"):
"Neat Money" 
"Neat-Invests"
"Money Holder" 
"Stock Keeper"
"Keep It Clear" => La que mas me gusta

**Comment by gabrielrostan** [comment]
podria ser algo como "Trad-Con" de trading control o "Trade Movement" haciendo alguna abreviatura.

**Comment by ahroncich7** [comment]
> podria ser algo como "Trad-Con" de trading control o "Trade Movement" haciendo alguna abreviatura.

"Trades Keeper" también podrías ser

**Comment by TomiLencina** [comment]
"Keep it clear" me parece el nombre idóneo para nuestro proyecto. La traducción especifica seria "mantenlo claro" y es justamente hacia donde estamos apuntando nuestro proyecto, es decir nuestro objetivo es optimizar-facilitar el control de las inversiones de nuestros usuarios(para que desde una misma app puedan ver sus valores que están dispersos en distintos exchanges, por decir un ejemplo).

Nuestro fin es que desde nuestra app los users se enteren de si están ganando o perdiendo dinero en tiempo real y todo desde la misma plataforma. "Keep it clear" engloba de una manera divertida esto.

Además suena como Kepit clir. No es difícil de pronunciar y es fácil de recordar...

**Comment by TomiLencina** [comment]
Y con respecto a nuestro grupo de desarrollo, sería clave que nos pongamos algún nombre ficticio como dice Ale.

Un ejemplo la empresa de Mateo Salvatto se llama Asteroid Technologies; y el software mas exitoso que desarrollaron es la app "Hablalo". 

Primero definiría el nombre de nuestra plataforma y luego nuestro nombre como empresa

**Comment by ahroncich7** [comment]
Si definimos unas 2 o 3 opciones, les puedo preguntar a un grupo de inversores (potenciales usuarios) cuál les parece mas viable. 
Es mas, se me acaba de ocurrir que capaz podemos hacer un formulario para relevar datos de estos prospectos con varias pautas para determinas sus necesidades y preferencias

**Comment by TomiLencina** [comment]
Genial, deberíamos trabajar en el formulario lo antes posible, para que si todo sale bien podamos presentar el nombre del proyecto en el sprint 0.

**Comment by Malvina989** [comment]
Está buena esa de preguntar Ale y dejar en un g

**Comment by Malvina989** [comment]
V
