### ISSUE TITLE
Crear formulario para estudio de mercado

### ISSUE THREAD

**Issue by ahroncich7** [TomiLencina/ISPC-Proyecto-integrador-full-stack-#8]
Genial, deberíamos trabajar en el formulario lo antes posible, para que si todo sale bien podamos presentar el nombre del proyecto en el sprint 0.

_Originally posted by @TomiLencina in https://github.com/TomiLencina/ISPC-Proyecto-integrador-full-stack-/issues/3#issuecomment-1262572468_
      
Crear un formulario para repartir entre potenciales usuarios para definir preferencias y necesidades

**Comment by ahroncich7** [comment]
Inicialmente, hay que agregar un .txt con los puntos que queramos agregar al form. 
Lo ideal sería crear una rama (vinculada a este issue) y en el crear un .txt para definir los campos del formulario colaborativamente.

**Comment by ahroncich7** [comment]
Pienso que el formato del formulario debería ser algo parecido a los siguiente:
- Una primera parte contando de que se trata (muy breve), algo como "Es una aplicación para poder llevar control de los activos, criptos y divisas que se compran y mantienen, todo en un mismo lugar"
De ahí, sugerir que tipo de contenidos les gustaria agregar en cada sección
Algo asi.

**Comment by pautnik** [comment]
Buenas, sí, me parece buena idea lo que propones! como primera parte hacer una introducción que indique el propósito de la app y también podría tener el "por qué" estamos realizando el formulario por ejemplo "para lograr que tenga una buena experiencia como usuario" y decidir bien que preguntar para que la información obtenida sea útil y poder determinar que les resultaría mas satisfactorio.
Si bien el formulario tendría una parte mas estructurada, por otro lado, que lo cuestionado sea mas como una conversación con los posibles usuarios y que puedan desarrollar opiniones.

**Comment by ahroncich7** [comment]
Claro. Tal cual. Ahí abrí una rama. Fijate que es la que está vinculada a este issue
